## cv2.TERM_CRITERIA_EPS / cv2.TERM_CRITERIA_MAX_ITER

ex) criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)

cv.TERM_CRITERIA_EPS, 0.001 - 정확도가 0.001이하면 종료한다.
cv.TERM_CRITERIA_MAX_ITER - 최대 반복 횟수가 30회가 되면 종료한다.

## np.mgrid

In [4]:
import numpy as np

if __name__ == "__main__":
    x1, y1 = np.mgrid[0:3, 0:5] # 각각 0부터 2까지 3행 5열 세로로, 0부터 4까지 3행 5열 가로로
    print("x1 : \n", x1)
    print("y1 : \n", y1)

    x2, y2 = np.mgrid[-1:1:3j, -1:1:5j] # 각각 3분할로 세로, 5분할로 가로

    print("x2 : \n", x2)
    print("y2 : \n", y2)

x1 : 
 [[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]]
y1 : 
 [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
x2 : 
 [[-1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.]]
y2 : 
 [[-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]]


In [11]:
import numpy as np

if __name__ == "__main__":
    print(np.mgrid[0:9,0:6]) # 9행 6열로 각각 세로로 0~8까지, 가로로 0~5까지
    """ 
        [[[0 0 0 0 0 0]
        [1 1 1 1 1 1]
        [2 2 2 2 2 2]
        [3 3 3 3 3 3]
        [4 4 4 4 4 4]
        [5 5 5 5 5 5]
        [6 6 6 6 6 6]
        [7 7 7 7 7 7]
        [8 8 8 8 8 8]]

        [[0 1 2 3 4 5]
        [0 1 2 3 4 5]
        [0 1 2 3 4 5]
        [0 1 2 3 4 5]
        [0 1 2 3 4 5]
        [0 1 2 3 4 5]
        [0 1 2 3 4 5]
        [0 1 2 3 4 5]
        [0 1 2 3 4 5]]] 
    """

    print(np.mgrid[0:9,0:6].T) # 2개의 반환값의 같은 열끼리 붙인다.
    """ 
        [[[0 0]
        [1 0]
        [2 0]
        [3 0]
        [4 0]
        [5 0]
        [6 0]
        [7 0]
        [8 0]]

        [[0 1]
        [1 1]
        [2 1]
        [3 1]
        [4 1]
        [5 1]
        [6 1]
        [7 1]
        [8 1]]

        [[0 2]
        [1 2]
        [2 2]
        [3 2]
        [4 2]
        [5 2]
        [6 2]
        [7 2]
        [8 2]]

        [[0 3]
        [1 3]
        [2 3]
        [3 3]
        [4 3]
        [5 3]
        [6 3]
        [7 3]
        [8 3]]

        [[0 4]
        [1 4]
        [2 4]
        [3 4]
        [4 4]
        [5 4]
        [6 4]
        [7 4]
        [8 4]]

        [[0 5]
        [1 5]
        [2 5]
        [3 5]
        [4 5]
        [5 5]
        [6 5]
        [7 5]
        [8 5]]]
    """

    print(np.mgrid[0:9,0:6].T.reshape(-1, 2))
    """
        [[0 0]
        [1 0]
        [2 0]
        [3 0]
        [4 0]
        [5 0]
        [6 0]
        [7 0]
        [8 0]
        [0 1]
        [1 1]
        [2 1]
        [3 1]
        [4 1]
        [5 1]
        [6 1]
        [7 1]
        [8 1]
        [0 2]
        [1 2]
        [2 2]
        [3 2]
        [4 2]
        [5 2]
        [6 2]
        [7 2]
        [8 2]
        [0 3]
        [1 3]
        [2 3]
        [3 3]
        [4 3]
        [5 3]
        [6 3]
        [7 3]
        [8 3]
        [0 4]
        [1 4]
        [2 4]
        [3 4]
        [4 4]
        [5 4]
        [6 4]
        [7 4]
        [8 4]
        [0 5]
        [1 5]
        [2 5]
        [3 5]
        [4 5]
        [5 5]
        [6 5]
        [7 5]
        [8 5]]
    """

    objp = np.zeros((6*9, 3), dtype=np.float32)
    objp[:, :2] = np.mgird[0:9, 0:6].T.reshape(-1, 2)
    print(objp)

    """
        [[0. 0. 0.]
        [1. 0. 0.]
        [2. 0. 0.]
        [3. 0. 0.]
        [4. 0. 0.]
        [5. 0. 0.]
        [6. 0. 0.]
        [7. 0. 0.]
        [8. 0. 0.]
        [0. 1. 0.]
        [1. 1. 0.]
        [2. 1. 0.]
        [3. 1. 0.]
        [4. 1. 0.]
        [5. 1. 0.]
        [6. 1. 0.]
        [7. 1. 0.]
        [8. 1. 0.]
        [0. 2. 0.]
        [1. 2. 0.]
        [2. 2. 0.]
        [3. 2. 0.]
        [4. 2. 0.]
        [5. 2. 0.]
        [6. 2. 0.]
        [7. 2. 0.]
        [8. 2. 0.]
        [0. 3. 0.]
        [1. 3. 0.]
        [2. 3. 0.]
        [3. 3. 0.]
        [4. 3. 0.]
        [5. 3. 0.]
        [6. 3. 0.]
        [7. 3. 0.]
        [8. 3. 0.]
        [0. 4. 0.]
        [1. 4. 0.]
        [2. 4. 0.]
        [3. 4. 0.]
        [4. 4. 0.]
        [5. 4. 0.]
        [6. 4. 0.]
        [7. 4. 0.]
        [8. 4. 0.]
        [0. 5. 0.]
        [1. 5. 0.]
        [2. 5. 0.]
        [3. 5. 0.]
        [4. 5. 0.]
        [5. 5. 0.]
        [6. 5. 0.]
        [7. 5. 0.]
        [8. 5. 0.]]
    """

[[[0 0 0 0 0 0]
  [1 1 1 1 1 1]
  [2 2 2 2 2 2]
  [3 3 3 3 3 3]
  [4 4 4 4 4 4]
  [5 5 5 5 5 5]
  [6 6 6 6 6 6]
  [7 7 7 7 7 7]
  [8 8 8 8 8 8]]

 [[0 1 2 3 4 5]
  [0 1 2 3 4 5]
  [0 1 2 3 4 5]
  [0 1 2 3 4 5]
  [0 1 2 3 4 5]
  [0 1 2 3 4 5]
  [0 1 2 3 4 5]
  [0 1 2 3 4 5]
  [0 1 2 3 4 5]]]


## glob.glob

In [7]:
import glob

if __name__ == "__main__":
    output1 = glob.glob('*.txt')    # *는 임의 길이의 모든 문자열
    print(output1)

    output2 = glob.glob("file?.*")  # ?는 한자리의 문자
    print(output2)

    output3 = glob.glob("**", recursive=True)   # **로 recursive=True 설정하면 모든 하위 디렉토리까지 탐색
    print(output3)


['File01.txt', 'File02.txt', 'File03.txt']
['File1.bmp', 'File2.jpg', 'File3.mp4']
['File01.txt', 'File02.txt', 'File03.txt', 'File1.bmp', 'File2.jpg', 'File3.mp4', 'FunctionTest.ipynb', 'SubDirectory', 'SubDirectory\\File1_sub.txt']


## cv2.findChessboardCorners()

In [6]:
import cv2 as cv

if __name__ == "__main__":
    img = cv.imread("C:\\Users\\Autonav\\github_repo\\ComputerVision\\BasicExercise_py\\chessboard.jpg")
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

    # Find the chess board corners
    
    print("True case")
    print("-----------------------------")
    ret, corners = cv.findChessboardCorners(gray, (9,6), None)

    print(ret)  # True
    print(corners)  # 9*6개의 코너 좌표 반환

    print("False case")
    print("-----------------------------")
    ret, corners = cv.findChessboardCorners(gray, (7,6), None)

    print(ret)  # False
    print(corners)  # False라서 None 반환


True case
-----------------------------
True
[[[448.03592 323.40137]]

 [[409.0458  324.1153 ]]

 [[370.11862 323.8043 ]]

 [[331.64697 323.54984]]

 [[294.01416 323.0456 ]]

 [[256.30258 322.56174]]

 [[219.05083 321.9335 ]]

 [[182.17567 320.94577]]

 [[145.84607 320.55984]]

 [[450.63834 291.29047]]

 [[411.07516 290.58997]]

 [[370.6007  290.38324]]

 [[331.76688 289.47714]]

 [[292.82123 288.69424]]

 [[254.88704 287.39072]]

 [[216.92496 286.5141 ]]

 [[179.5726  285.42142]]

 [[142.8598  284.40955]]

 [[453.84695 254.36232]]

 [[412.38107 253.71275]]

 [[371.44388 252.71384]]

 [[331.5086  251.57193]]

 [[292.69006 250.93005]]

 [[254.1271  250.11034]]

 [[215.99852 249.18568]]

 [[178.2653  248.29561]]

 [[140.71875 247.60873]]

 [[454.619   214.33566]]

 [[413.03653 213.69554]]

 [[372.0375  213.2795 ]]

 [[331.9805  212.79706]]

 [[292.74265 212.22867]]

 [[253.74591 211.63545]]

 [[216.117   210.98746]]

 [[178.00311 210.20142]]

 [[140.04596 209.978  ]]

 [[454.58487 173.65

## cv2.cornerSubPix()

In [9]:
import numpy as np
import cv2 as cv

if __name__ == "__main__":
    # termination criteria
    criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)

    # prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
    objp = np.zeros((6*9,3), np.float32)
    objp[:,:2] = np.mgrid[0:9,0:6].T.reshape(-1,2)

    # Arrays to store object points and image points from all the images.
    objpoints = [] # 3d point in real world space
    imgpoints = [] # 2d points in image plane.
    
    # without refining
    img = cv.imread("C:\\Users\\Autonav\\github_repo\\ComputerVision\\BasicExercise_py\\chessboard3.jpg")
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

    # Find the chess board corners
    ret, corners = cv.findChessboardCorners(gray, (9,6), None)

    # Draw and display the corners
    cv.drawChessboardCorners(img, (9,6), corners, ret)
    cv.imshow('img', img)

    # with refining

    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)
        corners2 = cv.cornerSubPix(gray, corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners2)

    # Draw and display the corners
    cv.drawChessboardCorners(img, (9,6), corners2, ret)
    cv.imshow('img2', img)
    
    cv.waitKey()
    cv.destroyAllWindows()

## cv2.drawChessoardCorners()

cv2.drawChessoardCorners(image, patternSize, corners, patternWasFound)

image - 컬러 이미지

patternSize - 체스보드 내부에 있는 코너의 갯수를 (행,열)로 나타낸다.

corners - cv2.findChessboardCorners 찾았거나 cv2.cornerSubPixel로 정제한 찾은 corner 좌표들이 담긴 자료형을 넣는다.

patternWasFound - cv2.findChessboardCorners로 코너를 찾았는지 못찾았는지 반환되서 나온 ret 값을 넣는다.
